language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: LdHWHUhWbOrBusXwpr/SaiSaQg9q67OZvrYhiNbkCl8alexMcnEG1bLxWZDeTsllc3Y1TaDgPatb+aoSaIbfJ31QsSxcy6XANUGaCS7mk4k1zZ7b9O1FMY97Hz494LKdKXJegdqNRLd8FbdLTzC+NeGqQj9k/ar90V0HnaeL6zDjjCZnKAYy+gBgQUdCVbQd3Gjnp5o1ZG7txIGVaxWb/sITLdXTf33kJ0AKhpU6IscLZnFyuDzJH+CuN1dvgILswYdau9/EQbvdVs5vNV/ZwDPrbFTYRlZm9xFscrWBhdhLKkr6TW1WaranHoLhutTVoXsfLcs+KgKXMykE8vO2mPEI6az9VUscdGxFRBz6gxeeL44XOaTWdLqulvsaDx2VX3R6aiQ5Y69tlxZ9vLfgGxEURIODfwo+l7TYcbrU1WP5W7Pk/VfMc3wugQXAk+zE2Rku9p7ldV4/kuTev/9q9WNZB/9Q95/gVImp84D6fskU6diAGD7AgP+73xbrkYwE80AZ782Y8leTFCtx7uUk2kbCfvp/6brxOB0SMwKnrNG7SroSA7iMPxN4DYRWyoES56GwhBAdu5hhOjhe+yZOqxcLFcON1vDvcEhEtJONa5FsFpSja9tl1Y4dZ5d0a7UhjoM68wvZH7tpunpFM6NDjml0UEQtmZjosiepP/gkwdA=

